Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"

  config.vm.network "private_network", ip: "192.168.10.10"

  config.hostsupdater.aliases = ["development_app.local"]

  # Synced folder -- connection both ways

  # config.vm.synced_folder("Path_to_origin_folder_to_sync", "path_in_machine_to_create_synced_folder")

  config.vm.synced_folder("app", "/app")

  config.vm.provision "shell", path: "provision.sh"

end
